# BUILD STAGE
FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o migrate ./cmd/migrate/main.go

# FINAL STAGE
FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /app/migrate /migrate
USER nonroot:nonroot
ENTRYPOINT ["/migrate"]
