# BUILD STAGE
FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG APP_VERSION=dev
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-X main.Version=${APP_VERSION}" -o worker ./cmd/worker/main.go

# FINAL STAGE
FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /app/worker /worker
USER nonroot:nonroot
ENTRYPOINT ["/worker"]
