sonar.organization=toanle88
sonar.projectKey=toanle88_healthcheck
sonar.projectName=Healthcheck
sonar.sources=cmd,internal,web/src
sonar.tests=cmd,internal,web/src
sonar.test.inclusions=**/*_test.go,web/src/**/*.test.ts,web/src/**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/vendor/**,infra/**,web/dist/**,web/coverage/**,web/playwright-report/**
sonar.go.coverage.reportPaths=coverage.out
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info
